apiVersion: v1
kind: ConfigMap
metadata:
  name: certificates-config
data:
  {{- if .Values.LDAP_CERTIFICATE_PATH }}
  ldap_certificate: {{ .Files.Get .Values.LDAP_CERTIFICATE_PATH | quote }}
  {{- end }}