apiVersion: v1
kind: Secret
metadata:
  name: certificates-secret
type: Opaque
data:
  {{- if .Values.SSL_CRT_PATH }}
  nginx_ssl_crt: {{ .Files.Get .Values.SSL_CRT_PATH | b64enc }}
  {{- end }}
  {{- if .Values.SSL_KEY_PATH }}
  nginx_ssl_key: {{ .Files.Get .Values.SSL_KEY_PATH | b64enc }}
  {{- end }}

