apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysqldb
  name: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: "vm_scheduler"
        - name: MYSQL_ROOT_PASSWORD
          value: {{ required "MYSQL_ROOT_PASSWORD is required!" .Values.MYSQL_ROOT_PASSWORD | quote }}
        image: mysql:5.7
        imagePullPolicy: "IfNotPresent"
        name: mysqldb
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysqldb-persistentvolumeclaim
      restartPolicy: Always
      serviceAccountName: {{ default "" .Values.serviceAccountName | quote }}
      volumes:
      - name: mysqldb-persistentvolumeclaim
        persistentVolumeClaim:
          claimName: mysqldb-persistentvolumeclaim
