apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysqldb-persistentvolumeclaim
  name: mysqldb-persistentvolumeclaim
spec:
  accessModes: [ "ReadWriteMany" ]
{{- if .Values.volumeClaimSpec }}
{{ toYaml .Values.volumeClaimSpec | indent 2 }}
{{- end }}
  resources:
    requests:
      storage: 1Gi