apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: swisscomcloud/esc-vm-scheduler-nginx:latest
        imagePullPolicy: "IfNotPresent"
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /app/staticfiles
          name: static-volume
      restartPolicy: Always
      serviceAccountName: {{ default "" .Values.serviceAccountName | quote }}
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-volume
