apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        {{- if .Values.SSL_CRT_PATH }}
        image: swisscomcloud/esc-vm-scheduler-nginx-ssl:latest
        {{- else }}
        image: swisscomcloud/esc-vm-scheduler-nginx:latest
        {{- end }}
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - name: static-volume
          mountPath: /app/staticfiles
        - name: ssl-certificates
          mountPath: /etc/ssl/certs
          readOnly: true
      restartPolicy: Always
      serviceAccountName: {{ default "" .Values.serviceAccountName | quote }}
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-volume
      - name: ssl-certificates
        secret:
          secretName: certificates-secret
          items:
          {{- if .Values.SSL_CRT_PATH }}
          - key: nginx_ssl_crt
            path: escvmscheduler-nginx-selfsigned.crt
          {{- end }}
          {{- if .Values.SSL_KEY_PATH }}
          - key: nginx_ssl_key
            path: escvmscheduler-nginx-selfsigned.key
          {{- end }}