apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx_conf: |-
    upstream vm_scheduler {
      server web:80;
    }

    server {
        {{- if .Values.SSL_CRT_PATH }}
        listen 443 ssl;
        ssl_certificate     /etc/ssl/certs/escvmscheduler-nginx-selfsigned.crt;
        ssl_certificate_key /etc/ssl/certs/escvmscheduler-nginx-selfsigned.key;
        {{- else }}
        listen 80;
        {{- end }}
        proxy_read_timeout 180s;
        server_tokens off; # Hide nginx version - For security reasons
        location / {
            proxy_pass http://vm_scheduler;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
        }
        location /staticfiles/ {
            alias /app/staticfiles/;
        }
    }