apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - env:
        - name: ALLOWED_HOSTS
          value: {{ default "*" .Values.ALLOWED_HOSTS | quote }}
        - name: DEBUG
          value: "0"
        - name: INITIAL_ADMIN_PASSWORD
          value: {{ required "INITIAL_ADMIN_PASSWORD is required!" .Values.INITIAL_ADMIN_PASSWORD | quote }}
        {{- if .Values.INITIAL_USER_PASSWORD }}
        - name: INITIAL_USER_PASSWORD
          value: {{ .Values.INITIAL_USER_PASSWORD | quote }}
        {{- end }}
        {{- if .Values.LDAP_BASE_DN }}
        - name: LDAP_BASE_DN
          value: {{ .Values.LDAP_BASE_DN | quote }}
        {{- end }}
        {{- if .Values.LDAP_BIND_DN }}
        - name: LDAP_BIND_DN
          value: {{ .Values.LDAP_BIND_DN | quote }}
        {{- end }}
        {{- if .Values.LDAP_BIND_PASSWORD }}
        - name: LDAP_BIND_PASSWORD
          value: {{ .Values.LDAP_BIND_PASSWORD | quote }}
        {{- end }}
        {{- if .Values.LDAP_GROUP_DN }}
        - name: LDAP_GROUP_DN
          value: {{ .Values.LDAP_GROUP_DN | quote }}
        {{- end }}
        {{- if .Values.LDAP_IGNORE_CERT }}
        - name: LDAP_IGNORE_CERT
          value: {{ .Values.LDAP_IGNORE_CERT | quote }}
        {{- end }}
        {{- if .Values.LDAP_SERVER_URI }}
        - name: LDAP_SERVER_URI
          value: {{ .Values.LDAP_SERVER_URI | quote }}
        {{- end }}
        {{- if .Values.LDAP_START_TLS }}
        - name: LDAP_START_TLS
          value: {{ .Values.LDAP_START_TLS | quote }}
        {{- end }}
        {{- if .Values.LDAP_SUPERUSER_GROUP_DN }}
        - name: LDAP_SUPERUSER_GROUP_DN
          value: {{ .Values.LDAP_SUPERUSER_GROUP_DN | quote }}
        {{- end }}
        {{- if .Values.LDAP_WITH_LOCAL_AUTH }}
        - name: LDAP_WITH_LOCAL_AUTH
          value: {{ .Values.LDAP_WITH_LOCAL_AUTH | quote }}
        {{- end }}
        {{- if .Values.LDAP_GROUP_TYPE }}
        - name: LDAP_GROUP_TYPE
          value: {{ .Values.LDAP_GROUP_TYPE | quote }}
        {{- end }}
        - name: MYSQL_ROOT_PASSWORD
          value: {{ required "MYSQL_ROOT_PASSWORD is required!" .Values.MYSQL_ROOT_PASSWORD | quote }}
        - name: SECRET_KEY
          value: {{ required "SECRET_KEY is required!" .Values.SECRET_KEY | quote }}
        image: swisscomcloud/esc-vm-scheduler-web:latest
        imagePullPolicy: "IfNotPresent"
        name: web
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - name: static-volume
          mountPath: /app/staticfiles
        - name: ldap-certificate
          mountPath: /etc/ssl/certs
      restartPolicy: Always
      serviceAccountName: {{ default "" .Values.serviceAccountName | quote }}
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-volume
      - name: ldap-certificate
        configMap:
          name: certificates-config
          items:
          {{- if .Values.LDAP_CERTIFICATE_PATH }}
          - key: ldap_certificate
            path: ldap_cert.pem
          {{- end }}
