#############################
### Local User Passwords: ###
#############################

### INITIAL_USER_PASSWORD - For user named "user" - only relevant if no LDAP is in use
INITIAL_USER_PASSWORD: "password"
### INITIAL_ADMIN_PASSWORD - For user named "admin" - exists in any case
INITIAL_ADMIN_PASSWORD: "password"



#################################
### Django Security Settings: ###
#################################

### SECRET_KEY - used to provide cryptographic signing, should be set to a unique, unpredictable value.
SECRET_KEY: "setArandomKey"
### ALLOWED_HOSTS - A list of strings representing the host/domain names that this Django site can serve. This is a security measure to prevent HTTP Host header attacks, which are possible even under many seemingly-safe web server configurations.
ALLOWED_HOSTS: "localhost,0.0.0.0,127.0.0.1,vm-scheduler,yourdomain.com" 



################################
### Database Settings: #########
################################

### MYSQL_ROOT_PASSWORD - Root password for the MySQL Databased used for this application.
MYSQL_ROOT_PASSWORD: "setAsecurePassword"



################################
### TLS/SSL Settings: ##########
################################

### SSL_CRT_PATH - Path to SSL/TLS .crt file relative to Chart.yaml (optional)
SSL_CRT_PATH: "escvmscheduler-nginx-selfsigned.crt"
### SSL_KEY_PATH - Path to SSL/TLS .key file relative to Chart.yaml (optional)
SSL_KEY_PATH: "escvmscheduler-nginx-selfsigned.key"

#################################
### LDAP Settings (optional): ###
#################################

### LDAP_SERVER_URI - The URI for the LDAP Server for login
LDAP_SERVER_URI: "ldap://ldap.forumsys.com:389"
### LDAP_BIND_DN - The object/credential used for authenticating against LDAP
LDAP_BIND_DN: "cn=read-only-admin,dc=example,dc=com"
### LDAP_BIND_PASSWORD - The object/credential's password used for authenticating against LDAP
LDAP_BIND_PASSWORD: "password"
### LDAP_BASE_DN - The point from where the LDAP server will search for users
LDAP_BASE_DN: "DC=example,DC=com"
### LDAP_GROUP_DN - The group containing users that shall get regular user rights
LDAP_GROUP_DN: ""
### LDAP_SUPERUSER_GROUP_DN - The group containing users that shall get admin rights  (optional)
LDAP_SUPERUSER_GROUP_DN: "ou=mathematicians,dc=example,dc=com"
### LDAP_WITH_LOCAL_AUTH - Enables local "admin" user in addition to LDAP users
LDAP_WITH_LOCAL_AUTH: true
### LDAP_START_TLS - Enable LDAP StartTLS (optional)
LDAP_START_TLS: false
### LDAP_IGNORE_CERT - Ignore TLS/LDAPS certificates (optional)
LDAP_IGNORE_CERT: true
### LDAP_CERTIFICATE_PATH - Path to LDAP .pem certificate relative to Chart.yaml (optional)
LDAP_CERTIFICATE_PATH: "ldap_cert.pem"

#################################
### Kubernetes Settings: ########
#################################

### loadBalancerIP - If not specified, the loadBalancer is set up with an ephemeral IP address. (optional)
# loadBalancerIP: 1.1.1.1
### serviceAccountName - If not specified, the "default" Service Account will be used (optional)
# serviceAccountName: ""
### volumeClaimSpec - Set the storageClassName & volumeMode for the two persitent volume claims (optional)
# volumeClaimSpec:
#   storageClassName: nfs-client
#   volumeMode: Filesystem